sudo: true
language: go
go:
  - 1.9.1
  - 1.10.1
  - 1.10.2
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - go get -v ./...
  - go get -v github.com/go-sql-driver/mysql
  - go get -v github.com/mattn/go-sqlite3
  - go get -v github.com/modocache/gover
  - go get -v github.com/mattn/goveralls
script:
  - go fmt ./...
  - go vet ./...
  - go test -v -coverprofile=sqlite3.coverprofile -run Sqlite3 
  - go test -v -coverprofile=sql.coverprofile -run MysqlSql 
  - go test -v -coverprofile=sql.coverprofile -run MysqlDB
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
